baseURL = 'https://technicalsummaries.com/'
languageCode = 'en-us'
title = 'Technical summaries'
theme = 'hugo-book'
disqusShortname = "technical-summaries"

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
disablePathToLower = true
enableGitInfo = true


[params]
  BookTheme = 'light'
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/mateuszbroja/technicalsummaries.com'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  BookEditPath = 'edit/main'
  BookCommitPath = 'commit'